project:
  type: website
  render: 
    - "*.qmd"

execute: 
  freeze: auto
  
website:
  title: "Neighborhood Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: assignments/index.qmd
        text: Assignments
      - href: howto/index.qmd
        text: "How To"
      - href: resources/index.qmd
        text: Resources
      - href: "https://github.com/UP570-S24/discussion"
        icon: github
        text: Discussion
    search: true
  favicon: favicon.png
  page-footer:
    left: "Content {{< fa regular copyright >}} Andrew J. Greenlee"
    right: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) </br> Website Code on [Github {{< fa brands github >}}]({{< var course.github >}})"

  sidebar:
    - title: "Schedule"
      contents:
        - section: "Schedule Overview"
          contents:
            - text: "Course Schedule"
              file: schedule/index.qmd
        - section: "Course Introduction"
          contents:
            - text: "1. Course Introduction"
              file: schedule/01_introduction.qmd
            - text: "2. What is a Neighborhood?"
              file: schedule/02_neighborhood.qmd
            - text: "3. Building a Data Pipeline"
              file: schedule/03_datapipeline.qmd
            - text: "4. Working with Tidy Data"
              file: schedule/04_tidydata.qmd
            - text: "5. Working with Tidy Data"
              file: schedule/05_tidydata.qmd
            - text: "6. Describing Places"
              file: schedule/06_sharing.qmd
            - text: "7. Communicating Complex Information"
              file: schedule/07_communicating.qmd
        - section: "Strategies for Analysis"
          contents:
            - text: "8. Describing Places"
              file: schedule/08_places.qmd
            - text: "9. Describing Places"
              file: schedule/09_places.qmd
            - text: "10. Population and the Census"
              file: schedule/10_census.qmd
            - text: "11. Population and the Census"
              file: schedule/11_census.qmd
            - text: "12. Segregation"
              file: schedule/12_segregation.qmd
            - text: "13. Segregation"
              file: schedule/13_segregation.qmd
            - text: "14. Neighborhood Change"
              file: schedule/14_neighborhood.qmd
            - text: "15. Neighborhood Change"
              file: schedule/15_neighborhood.qmd
            - text: "16. Place Opportunity"
              file: schedule/16_opportunity.qmd
            - text: "17. Place Opportunity"
              file: schedule/17_opportunity.qmd
            - text: "18. Transit Equity"
              file: schedule/18_transequity.qmd
            - text: "19. Transit Equity"
              file: schedule/19_transequity.qmd
            - text: "20. Health Equity"
              file: schedule/20_healthequity.qmd
            - text: "21. Health Equity"
              file: schedule/21_healthequity.qmd
            - text: "22. Final Project Check-In"
              file: schedule/22_CheckIn.qmd
            - text: "23. Final Project Check-In"
              file: schedule/23_CheckIn.qmd
        - section: "Course Wrap-Up"
          contents:
            - text: "24. Field Observation"
              file: schedule/24_fieldobs.qmd
            - text: "25. Field Observation"
              file: schedule/25_fieldobs.qmd
            - text: "26. Final Presentations"
              file: schedule/26_finalpresent.qmd
            - text: "27. Independent Work and Advising"
              file: schedule/27_indwork.qmd
            - text: "28. Final Presentations"
              file: schedule/28_finalpresent.qmd
            - text: "29. Final Presentations"
              file: schedule/29_finalpresent.qmd
    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignments/index.qmd
        - section: "Labs"
          contents:     
            - text: "Building a Data Pipeline"
              file: assignments/labs/01_datapipeline/01_datapipeline.qmd
            - text: "Sharing Your Work"
              file: assignments/labs/02_sharing/02_sharing.qmd
            - text: "Communicating Your Analysis"
              file: assignments/labs/03_communicating/03_communicating.qmd
            - text: "Describing Places"
              file: assignments/labs/04_describing_places/04_describing.qmd
            - text: "Population and the Census"
              file: assignments/labs/05_population_census/05_census.qmd
            - text: "Segregation"
              file: assignments/labs/06_segregation/06_segregation.qmd
            - text: "Neighborhood Change"
              file: assignments/labs/07_neighborhood_change/07_neighborhood_change.qmd
            - text: "Place Opportunity"
              file: assignments/labs/08_place_opportunity/08_placeopportunity.qmd
            - text: "Transportation Equity"
              file: assignments/labs/09_transportation_equity/measuring-transportation-equity.qmd
            - text: "Neighborhood Health Equity"
              file: assignments/labs/10_health_equity/10_health_equity.qmd
        - section: "Assignments"
          contents:
            - text: "Place Selection Memorandum"
              file: assignments/01_place_selection.qmd
            - text: "Place Background Memorandum"
              file: assignments/02_place_background.qmd
            - text: "Population Memorandum"
              file: assignments/03_population.qmd
            - text: "Policy Memorandum"
              file: assignments/04_policy.qmd
            - text: "Term Assignment"
              file: assignments/05_term.qmd
            - text: "Ph.D. Term Assignment"
              file: assignments/06_phd.qmd
              
    - title: "How To"
      contents:
        - section: "Get Started"
          contents:
            - text: "Introduction"
              file: howto/index.qmd
            - text: "Set Up R and RStudio"
              file: howto/setupr.qmd
        - section: "R Basics"
          contents:
            - text: "Lesson 1: Basic Principles"
              file: howto/rbasics_01.qmd
            - text: "Lesson 2: Manipulating Data Frames"
              file: howto/rbasics_02.qmd
            - text: "Lesson 3: Tidy Data"
              file: howto/rbasics_03.qmd
        - section: "Communicate Your Analysis"
          contents:
            - text: "Planning and Writing By The Numbers"
              file: howto/PWBTN/PWBTN.qmd
        - section: "Code Base"
          contents:
        - section: "Share Your Work"
          contents:             

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resources/index.qmd
        - section: "Resources"
          contents:
            - text: "Course Texts"
              file: resources/textbook.qmd
            - text: "Neighborhood Analysis"
              file: resources/analysis.qmd
            - text: "Data Sources"
              file: resources/data.qmd
            - text: "Inspiration"
              file: resources/inspiration.qmd

format:
  html:
    theme:
      light: [flatly, custom.scss]
    css: 
      - styles.css
    toc: true

editor: visual

