project:
  type: website
  render: 
    - "*.qmd"

execute: 
  freeze: auto
  
website:
  title: "Neighborhood Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: assignments/index.qmd
        text: Assignments
      - href: howto/index.qmd
        text: "How To"
      - href: resources/index.qmd
        text: Resources
      - href: "https://up570s23.slack.com/"
        icon: slack
        aria-label: Slack
    search: true
  favicon: favicon.png
  page-footer:
    left: "Content {{< fa regular copyright >}} Andrew J. Greenlee"
    right: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) </br> Website Code on [Github {{< fa brands github >}}]({{< var course.github >}})"

  sidebar:
    - title: "Schedule"
      contents:
        - section: "Schedule Overview"
          contents:
            - text: "Course Schedule"
              file: schedule/index.qmd
        - section: "Course Introduction"
          contents:
            - text: "1. Course Introduction"
              file: schedule/01_introduction.qmd
            - text: "2. What is a Neighborhood?"
              file: schedule/02_neighborhood.qmd
            - text: "3. Building a Data Pipeline"
              file: schedule/03_datapipeline.qmd
            - text: "4. Sharing Your Work"
              file: schedule/04_sharing.qmd
            - text: "5. Communicating Complex Information"
              file: schedule/05_communicating.qmd
            - text: "6. Describing Places"
              file: schedule/06_places.qmd
            - text: "7. Describing Places"
              file: schedule/07_places.qmd
        - section: "Strategies for Analysis"
          contents:
            - text: "8. Population and the Census"
              file: schedule/08_census.qmd
            - text: "9. Population and the Census"
              file: schedule/09_census.qmd
            - text: "10. Segregation"
              file: schedule/10_segregation.qmd
            - text: "11. Segregation"
              file: schedule/11_segregation.qmd
            - text: "12. Neighborhood Change"
              file: schedule/12_neighborhood.qmd
            - text: "13. Neighborhood Change"
              file: schedule/13_neighborhood.qmd
            - text: "14. Place Opportunity"
              file: schedule/14_opportunity.qmd
            - text: "15. Place Opportunity"
              file: schedule/15_opportunity.qmd
            - text: "16. Transit Equity"
              file: schedule/16_transequity.qmd
            - text: "17. Transit Equity"
              file: schedule/17_transequity.qmd
            - text: "18. Health Equity"
              file: schedule/18_healthequity.qmd
            - text: "19. Health Equity"
              file: schedule/19_healthequity.qmd
            - text: "20. Final Project Check-In"
              file: schedule/20_CheckIn.qmd
            - text: "21. Final Project Check-In"
              file: schedule/21_CheckIn.qmd
            - text: "22. Field Observation"
              file: schedule/22_fieldobs.qmd
            - text: "23. Field Observation"
              file: schedule/23_fieldobs.qmd
        - section: "Course Wrap-Up"
          contents:
            - text: "24. TBD"
              file: schedule/24_TBD.qmd
            - text: "25. TBD"
              file: schedule/25_TBD.qmd
            - text: "26. Final Presentations"
              file: schedule/26_finalpresent.qmd
            - text: "27. Independent Work and Advising"
              file: schedule/27_indwork.qmd
            - text: "28. Final Presentations"
              file: schedule/28_finalpresent.qmd
            - text: "29. Final Presentations"
              file: schedule/29_finalpresent.qmd
    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignments/index.qmd
        - section: "Labs"
          contents:     
            - text: "Building a Data Pipeline"
              file: assignments/labs/01_datapipeline/01_datapipeline.qmd
            - text: "Sharing Your Work"
              file: assignments/labs/02_sharing/02_sharing.qmd
            - text: "Communicating Your Analysis"
              file: assignments/labs/03_communicating/03_communicating.qmd
            - text: "Describing Places"
              file: assignments/labs/04_describing_places/04_describing.qmd
            - text: "Population and the Census"
              file: assignments/labs/05_population_census/05_census.qmd
            - text: "Segregation"
              file: assignments/labs/06_segregation/06_segregation.qmd
            - text: "Neighborhood Change"
              file: assignments/labs/07_neighborhood_change/07_neighborhood_change.qmd
            - text: "Place Opportunity"
              file: assignments/labs/08_place_opportunity/08_placeopportunity.qmd
            - text: "Transportation Equity"
              file: assignments/labs/09_transportation_equity/09_transportation_equity.qmd
            - text: "Neighborhood Health Equity"
              file: assignments/labs/10_health_equity/10_health_equity.qmd
        - section: "Assignments"
          contents:
            - text: "Place Selection Memorandum"
              file: assignments/01_place_selection.qmd
            - text: "Place Background Memorandum"
              file: assignments/02_place_background.qmd
            - text: "Population Memorandum"
              file: assignments/03_population.qmd
            - text: "Policy Memorandum"
              file: assignments/04_policy.qmd
            - text: "Term Assignment"
              file: assignments/05_term.qmd
            - text: "Ph.D. Term Assignment"
              file: assignments/06_phd.qmd
              
    - title: "How To"
      contents:
        - section: "Get Started"
          contents:
            - text: "Introduction"
              file: howto/index.qmd
            - text: "Set Up R and RStudio"
              file: howto/setupr.qmd
        - section: "Communicate Your Analysis"
          contents:
            - text: "Planning and Writing By The Numbers"
              file: howto/PWBTN/PWBTN.qmd
        - section: "Code Base"
          contents:
        - section: "Share Your Work"
          contents:             

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resources/index.qmd
        - section: "Resources"
          contents:
            - text: "Course Texts"
              file: resources/textbook.qmd
            - text: "Neighborhood Analysis"
              file: resources/analysis.qmd
            - text: "Data Sources"
              file: resources/data.qmd
            - text: "Inspiration"
              file: resources/inspiration.qmd

format:
  html:
    theme:
      light: [flatly, custom.scss]
    css: 
      - styles.css
    toc: true

editor: visual

