---
title: "Course Introduction"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

Welcome to UP 570: Neighborhood Analysis! This session serves as our introduction to the class and an opportunity to start exploring how we will work together over the course of the semester. We will introduce ourselves and discuss how we will learn together. We'll also think through two foundational questions:

1.  What is a neighborhood?
2.  Why do neighborhoods matter?

## Before Class

-   Bookmark this website <https://up570s24.netlify.app> so you can access it easily.
-   Join our course [Github Discussion Forum](%7B%7B%3C%20var%20course.discuss%20%3E%7D%7D)
-   Read the [course syllabus](../syllabus/index.qmd) and bring questions with you.
-   Complete the course [introductory survey](%7B%7B%3C%20var%20course.survey%20%3E%7D%7D).
-   Join the Data Science in Planning (DSIP) Listserv (dsip-durp-l\@lists.illinois.edu) where members of our community can share opportunities things of interest.
    -   Choose the address with which you want to subscribe to the list - you should choose an address you can check frequently.
    -   Send a message to [sympa\@lists.illinois.edu](mailto:sympa@lists.illinois.edu) from the address you want to subscribe to the list.
    -   In the subject line of your message, type in subscribe dsip-durp-l Firstname Name (replace Firstname and Name with your preferred first name and last name).
    -   Leave the message body blank.
    -   After this you will recieve a message telling you whether your request was accepted or not.
- Watch this video which provides an overview of our course website and resources:

```{=html}
<div style="max-width:720px"><div style="position:relative;padding-bottom:60.972222222222%"><iframe id="kmsembed-1_l29o8rlx" width="720" height="439" src="https://mediaspace.illinois.edu/embed/secure/iframe/entryId/1_l29o8rlx/uiConfId/26883701/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="UP 570: Site Overview" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0"></iframe></div></div>
```

## Reflect

-   What are your goals for taking this class? What would you like to learn about neighborhoods?
-   What matters about neighborhoods? How have neighborhoods shaped your life?
-   What types of stories do we tend to tell about neighborhoods? How do these stories contextualize how neighborhoods "fit" within cities and their regions?

## Slides

## Resources for Further Exploration

Comprehensive Development Plan for Champaign - Urbana (1950) [{{< fa link >}}](https://cityofchampaign.sharepoint.com/City%20Documents%20Internal/WordPress%20Media%20Files/Planning%20and%20Development%20Department/Long%20Range%20Planning/Development%20Plan%20Champaign%20Urbana%201950.pdf?ga=1)
