---
title: "Health Equity"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

We will work in groups today to do analysis and storytelling as part of the health equity lab. As mentioned in class on Monday, this lab will focus less on technical details and more on storytelling and interpretation of indicators.

## Group Assignments

For this assignment, you will work in three groups:

### Housing
Gabriela A.
Dakshinya B.
Dominic C.
Ar'Mand E.
Dasom H.
Shinmyeong H.
Tushar K.
Jenifer M.
Tillie P.
Anna S.

### Poverty
Siti A.
Bhagyashree
Natalie C.
Luisa P.
Erin H.
Joseph J.
Trinity L.
Anjana N.
Matthew R.
Alec T.

### Education
Hyndavi A.
Leela B.
Rithvika D.
Cole F.
Matthew H.
Nadia K.
Anukriti M.
Erin P.
Aabha S.
Zhenpeng Z.

Your group will present your narrative at the end of our class session. After class, please complete your lab reflection and push this to Github. There will be no other lab content or work for this week other than completing your own individual reflection on what we’ve done in small groups in class.

## Before Class

[Github Classroom Link](https://classroom.github.com/a/LU0SyJN9)

## Reflect

1.  What are some tropes or conventions we use to talk about individual health? Collective health?

2.  How might health disparities (at a neighborhood or population level) be connected to the many themes we've talked about in this class?

3.  Is population health a planning issue? What role do practitioners and researchers in planning have for influencing how we think and act around health at the neighborhood level?

## Slides

## Resources for Further Exploration
