---
title: "Final Presentations"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

We've made it to the end of the semester! Now is the time to share and celebrate your hard work. This week's sessions are devoted to sharing your final stories. You will each have eight very brief minutes to share your policy-informed stories with us. Please plan to use the entire time to present to us - we'll give written comments and feedback so you have the maximum amount of time for sharing your work.

## Today's Presenters

Reminder - each presenter has seven minutes to share.

### Arizona

**Joseph J.:** Campus Housing Policy at Arizona State University's (ASU) Tempe campus

### California

**Erin H.:** Shedding Light on Oakland's Informal Housing as a Response to Affordable Housing Crisis: Fruitvale Neighborhood

### Florida

**Anjana N.:** Regional Planning in Miami and Fort Lauderdale

**Anna S.:** Education disparities in Miami

**Leela B.:** Dynamics of Climate Gentrification within Miami

### Maryland

**Aabha S.:** Beyond the Rails: East-West Connect Policy

### Michigan

**Siti A.:** Is the Strategic Neighborhood Fund initiative successfully addressing urban decline in Detroit City, Michigan, and worth replication?

### Missouri

**Cole F.:** Comparing Gun Homicides & Third Places in St. Louis, MO

### Washington D.C.

**Erin P.:** Retaining Residents in the Southeast Quadrant Through Education

**Zhenpeng Z.:** The inequality Assessment of "Local North" and "Local South" in Washington, D.C.


## Providing Feedback

Please provide feedback to each other in the [following form](https://forms.gle/KUcP3Ek23b4uymQh6) - I will consolidate your written feedback on each presentation and will send it to you.
