---
title: "Final Presentations"
sidebar: true
toc: true
page-layout: full
format: html
editor: visual
---

## Session Description

We've made it to the end of the semester! Now is the time to share and celebrate your hard work. This week's sessions are devoted to sharing your final stories. You will each have eight very brief minutes to share your policy-informed stories with us. Please plan to use the entire time to present to us - we'll give written comments and feedback so you have the maximum amount of time for sharing your work.

## Today's Presenters

Reminder - each presenter has seven minutes to share.

### Illinois

**Alec T.:** Public Transit Accessibility in Normal, IL

**Anukriti M.:** Transit-Induced Displacement in Chicago

**Dasom H.:** A Study on the Impact of Chicago L Train (Elevated Train) Accessibility on Housing Prices: Comparison of Before and After COVID-19

**Dakshinya B.:** Lincoln Yards TIF

**Dominic C.:** Socio-economic hardships encountered by the Englewood community in Chicago

**Matt R.:** Near West Side Community Assessment

**Matthew H.:** Urban Morphometrics in Chicago

**Nadia K.:** Social Reproduction in Urban Spaces: A Spatial Regression Analysis of Public Housing and Child Care Facilities

**Shinmyeong H.:** Population Loss and Educational Accessibility in Chicago

## Providing Feedback

Please provide feedback to each other in the [following form](https://forms.gle/KUcP3Ek23b4uymQh6) - I will consolidate your written feedback on each presentation and will send it to you.
