---
title: "Schedule"
sidebar: true
toc: false
page-layout: full
format: html
editor: visual
---

Please find descriptions for our course sessions here - you will also find resources that will help you prepare for each session.

## Course Introduction

| Week   | Session   | Date       | Description                                                         |
|----------------|----------------|----------------|-------------------------|
| Week 1 | Session 1 | January 17 | [Course Introduction](01_introduction.qmd)                          |
| Week 2 | Session 2 | January 22 | [What is a Neighborhood?](02_neighborhood.qmd)                      |
| Week 2 | Session 3 | January 24 | [Building a Data Pipeline](03_datapipeline.qmd)                     |
| Week 3 | Session 4 | January 29 | [Sharing Your Work](04_sharing.qmd)                                 |
| Week 3 | Session 5 | January 31 | [Communicating Complex Information](05_communicating.qmd)       |
| Week 3 |           | February 5 | [Place Selection Memorandum](../assignments/01_place_selection.qmd) |
| Week 4 | Session 6 | February 5 | [Describing Places](06_places.qmd)                                  |
| Week 4 | Session 7 | February 7 | [Describing Places](07_places.qmd)                                  |

## Strategies for Analysis

|         |            |             |                                                                       |     |
|--------------|--------------|--------------|-----------------|--------------|
| Week    | Session    | Date        | Description                                                           |     |
| Week 5  | Session 8  | February 12 | [Population and the Census](08_census.qmd)                            |     |
| Week 5  | Session 9  | February 14 | [Population and the Census](09_census.qmd)                            |     |
| Week 5  |            | February 19 | [Place Background Memorandum](../assignments/02_place_background.qmd) |     |
| Week 6  | Session 10 | February 19 | [Segregation](10_segregation.qmd)                                     |     |
| Week 6  | Session 11 | February 21 | [Segregation](11_segregation.qmd)                                     |     |
| Week 7  | Session 12 | February 26 | [Neighborhood Change](12_neighborhood.qmd)                            |     |
| Week 7  | Session 13 | February 28 | [Neighborhood Change](13_neighborhood.qmd)                            |     |
| Week 7  |            | March 4     | [Population Memorandum](../assignments/03_population.qmd)             |     |
| Week 8  | Session 14 | March 4     | [Place Opportunity](14_opportunity.qmd)                               |     |
| Week 8  | Session 15 | March 6     | [Place Opportunity](15_opportunity.qmd)                               |     |
| Week 9  |            | March 11    | Spring Break                                                          |     |
| Week 9  |            | March 13    | Spring Break                                                          |     |
| Week 10 | Session 16 | March 18    | [Transportation Equity](16_transequity.qmd)                           |     |
| Week 10 | Session 17 | March 20    | [Transportation Equity](17_transequity.qmd)                           |     |
| Week 10 |            | March 25    | [Policy Memorandum](../assignments/04_policy.qmd)                     |     |
| Week 11 | Session 18 | March 25    | [Health Equity](18_healthequity.qmd)                                  |     |
| Week 11 | Session 19 | March 27    | [Health Equity](19_healthequity.qmd)                                  |     |
| Week 12 | Session 20 | April 1     | [Final Project Check-In](20_CheckIn.qmd)                              |     |
| Week 12 | Session 21 | April 3     | [Final Project Check-In](21_CheckIn.qmd)                              |     |
| Week 13 | Session 22 | April 8     | [Field Observation](22_fieldobs.qmd)                                  |     |
| Week 13 | Session 23 | April 10    | [Field Observation](23_fieldobs.qmd)                                  |     |
| Week 13 |            | April 15    | [Final Assignment](../assignments/05_term.qmd) First Draft            |     |

## Course Wrap-Up

| Week    | Session    | Date     | Description                                        |
|----------------|----------------|----------------|------------------------|
| Week 14 | Session 24 | April 15 | [TBD](24_TBD.qmd)                                  |
| Week 14 | Session 25 | April 17 | [TBD](25_TBD.qmd)                                  |
| Week 15 | Session 26 | April 22 | [Final Presentations](26_finalpresent.qmd)         |
| Week 15 | Session 27 | April 24 | [Independent Work (No Class)](27_indwork.qmd)      |
| Week 16 | Session 28 | April 29 | [Final Presentations](28_finalpresent.qmd)         |
| Week 16 | Session 29 | May 1    | [Final Presentations](29_finalpresent.qmd)         |
| Week 17 |            | May 10   | [Final Assignment Due](../assignments/05_term.qmd) |
